// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coefeyghedtsnsktrgqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZWZleWdoZWR0c25za3RyZ3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NjY3MjMsImV4cCI6MjA4NTQ0MjcyM30.a9n4T7Pc_QE-YIYsnzvqYlmyRwFD01M3T12zRkYblF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});